export const STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELAYED: 'DELAYED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  BODY_SHOP: 'BODY_SHOP',
  WATER_WASH: 'WATER_WASH',
  CANCELLED: 'CANCELLED',
};

export const STATUS_LABELS = {
  PENDING: 'Pending',
  ASSIGNED: 'Assigned',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
  DELAYED: 'Delayed',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  READY: 'Ready for Delivery',
  DELIVERED: 'Delivered',
  BODY_SHOP: 'Body Shop',
  WATER_WASH: 'Water Wash',
  CANCELLED: 'Cancelled',
  MECHANICAL_ASSIGNED: 'Mechanical Assigned',
  READY_FOR_DELIVERY: 'Ready for Delivery',
  JOB_CARD_CREATED: 'Job Card Created',
  ENTRY_CREATED: 'Entry Created',
  EXITED: 'Exited',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
};

export const STATUS_VARIANTS = {
  PENDING: 'warning',
  ASSIGNED: 'info',
  IN_PROGRESS: 'purple',
  COMPLETED: 'success',
  DELAYED: 'danger',
  APPROVED: 'success',
  REJECTED: 'danger',
  READY: 'primary',
  DELIVERED: 'secondary',
  BODY_SHOP: 'pink',
  WATER_WASH: 'teal',
  CANCELLED: 'secondary',
  MECHANICAL_ASSIGNED: 'info',
  READY_FOR_DELIVERY: 'primary',
  JOB_CARD_CREATED: 'success',
  ENTRY_CREATED: 'success',
  EXITED: 'danger',
  ACTIVE: 'success',
  INACTIVE: 'danger',
};

