import { ROLES } from '../constants/roles';

export const PERMISSIONS = {
  VIEW_ADMIN: [ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_GATE: [ROLES.GATE_SECURITY, ROLES.MANAGER, ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_CRM: [ROLES.CRM_TEAM, ROLES.MANAGER, ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_FLOOR: [ROLES.FLOOR_SUPERVISOR, ROLES.MANAGER, ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_BODY_SHOP: [ROLES.BODY_SHOP_SUPERVISOR, ROLES.MANAGER, ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_WATER_WASH: [ROLES.WATER_WASH_TEAM, ROLES.MANAGER, ROLES.SUPER_ADMIN, ROLES.MD],
  VIEW_MANAGEMENT: [ROLES.MANAGER, ROLES.MD, ROLES.SUPER_ADMIN],
  VIEW_EXECUTIVE: [ROLES.MD, ROLES.SUPER_ADMIN],
  VIEW_COMMON: Object.values(ROLES),
};

export const canAccess = (role, allowedRoles = []) => {
  if (!allowedRoles.length) return true;
  return allowedRoles.includes(role);
};

