export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',

  ADMIN_DASHBOARD: '/admin-dashboard',
  ADMIN_USERS: '/users',
  ADMIN_USER_NEW: '/users/new',
  ADMIN_USER_EDIT: '/users/edit/:slug',
  ADMIN_USER_VIEW: '/users/view/:slug',
  ADMIN_ROLES: '/roles',
  ADMIN_ROLE_PRIVILEGES: '/roles/privileges',
  ADMIN_ROLE_PRIVILEGES_EDIT: '/roles/privileges/edit/:slug',
  ADMIN_MASTER_CATEGORIES: '/master-categories',
  ADMIN_MASTER_CATEGORIES_NEW: '/master-categories/new',
  ADMIN_MASTER_CATEGORIES_EDIT: '/master-categories/edit/:slug',
  ADMIN_MASTER_ITEMS: '/master-items',
  ADMIN_MASTER_ITEMS_NEW: '/master-items/new',
  ADMIN_MASTER_ITEMS_EDIT: '/master-items/edit/:slug',
  ADMIN_MASTER_STATES: '/master-states',
  ADMIN_MASTER_STATES_NEW: '/master-states/new',
  ADMIN_MASTER_STATES_EDIT: '/master-states/edit/:slug',
  ADMIN_MASTER_BRANDS: '/master-brands',
  ADMIN_MASTER_BRANDS_NEW: '/master-brands/new',
  ADMIN_MASTER_BRANDS_EDIT: '/master-brands/edit/:slug',
  ADMIN_MASTER_DISTRICTS: '/master-districts',
  ADMIN_MASTER_DISTRICTS_NEW: '/master-districts/new',
  ADMIN_MASTER_DISTRICTS_EDIT: '/master-districts/edit/:slug',
  ADMIN_SERVICE_CENTERS: '/service-centers',
  ADMIN_SERVICE_CENTERS_NEW: '/service-centers/new',
  ADMIN_SERVICE_CENTERS_EDIT: '/service-centers/:id/edit',
  ADMIN_SERVICE_CENTERS_VIEW: '/service-centers/:id',
  ADMIN_LOCATIONS: '/locations',
  ADMIN_LOCATIONS_NEW: '/locations/new',
  ADMIN_LOCATIONS_EDIT: '/locations/edit/:slug',
  ADMIN_LOCATIONS_VIEW: '/locations/view/:slug',
  ADMIN_SETTINGS: '/system-settings',
  ADMIN_AUDIT_LOGS: '/audit-logs',
  ADMIN_AUDIT_LOG_DETAILS: '/audit-logs/:id',

  ADMIN_MODULES: '/modules',
  ADMIN_MODULES_NEW: '/modules/new',
  ADMIN_MODULES_EDIT: '/modules/edit/:slug',

  ADMIN_MASTER_STATUSES: '/master-statuses',
  ADMIN_MASTER_STATUSES_NEW: '/master-statuses/new',
  ADMIN_MASTER_STATUSES_EDIT: '/master-statuses/edit/:slug',

  GATE_DASHBOARD: '/gate-dashboard',
  GATE_ENTRY: '/gate-entry',
  GATE_EXIT: '/gate-exit',
  GATE_PENDING_SYNC: '/pending-sync',

  CRM_DASHBOARD: '/crm-dashboard',
  CRM_CREATE_JOB_CARD: '/job-cards/create',
  CRM_PENDING_JOB_CARDS: '/job-cards/pending',
  CRM_APPROVAL_FOLLOWUP: '/approval-followup',
  CRM_DELIVERY_READY: '/delivery-ready',
  CRM_ADDITIONAL_WORK: '/crm-additional-work',

  FLOOR_DASHBOARD: '/floor-dashboard',
  FLOOR_MECHANICAL_QUEUE: '/mechanical-queue',
  FLOOR_ASSIGN_MECHANIC: '/assign-mechanic',
  FLOOR_ADDITIONAL_WORK: '/additional-work',
  FLOOR_ADDITIONAL_WORK_NEW: '/additional-work/new',
  FLOOR_WORK_STATUS: '/work-status',

  BODY_SHOP_DASHBOARD: '/body-shop-dashboard',
  BODY_SHOP_QUEUE: '/body-shop-queue',
  BODY_SHOP_JOB: '/body-shop-jobs',
  BODY_SHOP_ASSIGN_MECHANIC: '/body-shop-assign-mechanic',
  BODY_SHOP_ADDITIONAL_WORK: '/body-shop-additional-work',
  BODY_SHOP_ADDITIONAL_WORK_NEW: '/body-shop-additional-work/new',
  BODY_SHOP_WORK_STATUS: '/body-shop-work-status',

  WATER_WASH_DASHBOARD: '/water-wash-dashboard',
  WATER_WASH_QUEUE: '/water-wash-queue',
  WATER_WASH_ASSIGN_MEMBER: '/water-wash-assign-member',
  WATER_WASH_JOB: '/water-wash-jobs',

  MANAGER_DASHBOARD: '/manager-dashboard',
  MANAGER_DELAYED_JOBS: '/delayed-jobs',
  MANAGER_PENDING_APPROVALS: '/pending-approvals',
  MANAGER_REPORTS: '/reports',
  MANAGER_JOB_CARDS: '/manager-job-cards',

  MD_DASHBOARD: '/md-dashboard',
  MD_EXECUTIVE_OVERVIEW: '/executive-overview',
  MD_PERFORMANCE_REPORT: '/performance-report',
  MD_SERVICE_KPI: '/service-kpi',
  MD_STAGE_SCHEDULES: '/md-stage-schedules',
  MD_STAGE_SCHEDULES_NEW: '/md-stage-schedules/new',
  MD_STAGE_SCHEDULES_EDIT: '/md-stage-schedules/:id/edit',

  KIOSK_TV: '/kiosk/tv',

  CUSTOMERS: '/customers',
  CUSTOMERS_NEW: '/customers/new',
  CUSTOMERS_EDIT: '/customers/:id/edit',
  VEHICLES: '/vehicles',
  VEHICLE_EDIT: '/vehicles/:id/edit',
  VEHICLE_HISTORY: '/vehicles/:id/history',
  JOB_CARDS: '/job-cards',
  JOB_CARD_VIEW: '/job-cards/view/:slug',
  JOB_CARD_EDIT: '/job-cards/edit/:slug',
  SERVICE_HISTORY: '/service-history',
  SERVICE_HISTORY_JOB_CARD: '/service-history/job-cards/:jobCardId',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};

