export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',

  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_NEW: '/admin/users/new',
  ADMIN_USER_EDIT: '/admin/users/:id/edit',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_ROLE_PRIVILEGES: '/admin/roles/privileges',
  ADMIN_ROLE_PRIVILEGES_EDIT: '/admin/roles/privileges/:id/edit',
  ADMIN_MASTER_CATEGORIES: '/admin/master/categories',
  ADMIN_MASTER_CATEGORIES_NEW: '/admin/master/categories/new',
  ADMIN_MASTER_CATEGORIES_EDIT: '/admin/master/categories/:id/edit',
  ADMIN_MASTER_ITEMS: '/admin/master/items',
  ADMIN_MASTER_ITEMS_NEW: '/admin/master/items/new',
  ADMIN_MASTER_ITEMS_EDIT: '/admin/master/items/:id/edit',
  ADMIN_MASTER_PRICING: '/admin/master/pricing',
  ADMIN_MASTER_PRICING_NEW: '/admin/master/pricing/new',
  ADMIN_MASTER_PRICING_EDIT: '/admin/master/pricing/:id/edit',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',

  GATE_DASHBOARD: '/gate/dashboard',
  GATE_ENTRY: '/gate/entry',
  GATE_EXIT: '/gate/exit',
  GATE_PENDING_SYNC: '/gate/pending-sync',

  CRM_DASHBOARD: '/crm/dashboard',
  CRM_CREATE_JOB_CARD: '/crm/job-cards/create',
  CRM_PENDING_JOB_CARDS: '/crm/job-cards/pending',
  CRM_APPROVAL_FOLLOWUP: '/crm/approvals/followup',
  CRM_DELIVERY_READY: '/crm/delivery-ready',
  CRM_ADDITIONAL_WORK: '/crm/additional-work',

  FLOOR_DASHBOARD: '/floor/dashboard',
  FLOOR_MECHANICAL_QUEUE: '/floor/mechanical-queue',
  FLOOR_ASSIGN_MECHANIC: '/floor/assign-mechanic',
  FLOOR_ADDITIONAL_WORK: '/floor/additional-work',
  FLOOR_WORK_STATUS: '/floor/work-status',

  BODY_SHOP_DASHBOARD: '/body-shop/dashboard',
  BODY_SHOP_QUEUE: '/body-shop/queue',
  BODY_SHOP_JOB: '/body-shop/jobs',

  WATER_WASH_DASHBOARD: '/water-wash/dashboard',
  WATER_WASH_QUEUE: '/water-wash/queue',
  WATER_WASH_JOB: '/water-wash/jobs',

  MANAGER_DASHBOARD: '/manager/dashboard',
  MANAGER_OPERATIONS: '/manager/operations',
  MANAGER_DELAYED_JOBS: '/manager/delayed-jobs',
  MANAGER_PENDING_APPROVALS: '/manager/pending-approvals',
  MANAGER_REPORTS: '/manager/reports',

  MD_DASHBOARD: '/md/dashboard',
  MD_EXECUTIVE_OVERVIEW: '/md/executive-overview',
  MD_PERFORMANCE_REPORT: '/md/performance-report',
  MD_SERVICE_KPI: '/md/service-kpi',

  KIOSK_TV: '/kiosk/tv',

  CUSTOMERS: '/customers',
  CUSTOMERS_NEW: '/customers/new',
  CUSTOMERS_EDIT: '/customers/:id/edit',
  VEHICLES: '/vehicles',
  JOB_CARDS: '/job-cards',
  JOB_CARD_EDIT: '/job-cards/:id/edit',
  SERVICE_HISTORY: '/service-history',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};

