export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',

  ADMIN_DASHBOARD: '/admin-dashboard',
  ADMIN_USERS: '/users',
  ADMIN_USER_NEW: '/users/new',
  ADMIN_USER_EDIT: '/users/:id/edit',
  ADMIN_ROLES: '/roles',
  ADMIN_ROLE_PRIVILEGES: '/roles/privileges',
  ADMIN_ROLE_PRIVILEGES_EDIT: '/roles/privileges/:id/edit',
  ADMIN_MASTER_CATEGORIES: '/master-categories',
  ADMIN_MASTER_CATEGORIES_NEW: '/master-categories/new',
  ADMIN_MASTER_CATEGORIES_EDIT: '/master-categories/:id/edit',
  ADMIN_MASTER_ITEMS: '/master-items',
  ADMIN_MASTER_ITEMS_NEW: '/master-items/new',
  ADMIN_MASTER_ITEMS_EDIT: '/master-items/:id/edit',
  ADMIN_SETTINGS: '/system-settings',
  ADMIN_AUDIT_LOGS: '/audit-logs',
  ADMIN_AUDIT_LOG_DETAILS: '/audit-logs/:id',

  GATE_DASHBOARD: '/gate-dashboard',
  GATE_ENTRY: '/gate-entry',
  GATE_EXIT: '/gate-exit',
  GATE_PENDING_SYNC: '/pending-sync',

  CRM_DASHBOARD: '/crm-dashboard',
  CRM_CREATE_JOB_CARD: '/job-cards/create',
  CRM_PENDING_JOB_CARDS: '/job-cards/pending',
  CRM_APPROVAL_FOLLOWUP: '/approval-followup',
  CRM_DELIVERY_READY: '/delivery-ready',
  CRM_ADDITIONAL_WORK: '/crm-additional-work',

  FLOOR_DASHBOARD: '/floor-dashboard',
  FLOOR_MECHANICAL_QUEUE: '/mechanical-queue',
  FLOOR_ASSIGN_MECHANIC: '/assign-mechanic',
  FLOOR_ADDITIONAL_WORK: '/additional-work',
  FLOOR_ADDITIONAL_WORK_NEW: '/additional-work/new',
  FLOOR_WORK_STATUS: '/work-status',

  BODY_SHOP_DASHBOARD: '/body-shop-dashboard',
  BODY_SHOP_QUEUE: '/body-shop-queue',
  BODY_SHOP_JOB: '/body-shop-jobs',

  WATER_WASH_DASHBOARD: '/water-wash-dashboard',
  WATER_WASH_QUEUE: '/water-wash-queue',
  WATER_WASH_JOB: '/water-wash-jobs',

  MANAGER_DASHBOARD: '/manager-dashboard',
  MANAGER_OPERATIONS: '/operations',
  MANAGER_DELAYED_JOBS: '/delayed-jobs',
  MANAGER_PENDING_APPROVALS: '/pending-approvals',
  MANAGER_REPORTS: '/reports',

  MD_DASHBOARD: '/md-dashboard',
  MD_EXECUTIVE_OVERVIEW: '/executive-overview',
  MD_PERFORMANCE_REPORT: '/performance-report',
  MD_SERVICE_KPI: '/service-kpi',

  KIOSK_TV: '/kiosk/tv',

  CUSTOMERS: '/customers',
  CUSTOMERS_NEW: '/customers/new',
  CUSTOMERS_EDIT: '/customers/:id/edit',
  VEHICLES: '/vehicles',
  JOB_CARDS: '/job-cards',
  JOB_CARD_EDIT: '/job-cards/:id/edit',
  SERVICE_HISTORY: '/service-history',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  SETTINGS: '/settings',
};

